# -*- coding: utf-8 -*-
"""model_merge.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11zsUdBbGOKagZMPanA0yE2sbEOJSIH9R
"""

#You can merge the mode using the script
!cat model.part_* > model.safetensors

#Alternatively you can use this python script
import os

# Directory where the model parts are stored
model_parts_dir = 'path_to_model_parts/'  # Adjust this path to where the parts are stored
output_file = 'model.safetensors'  # Name of the final merged model file

# List of model part files in the correct order
model_parts = [
    'model.part_aa',
    'model.part_ab',
    'model.part_ac',
    'model.part_ad',
    'model.part_ae',
    'model.part_af',
    'model.part_ag',
    'model.part_ah',
    'model.part_ai',
    'model.part_aj'
]

# Open the output file in write-binary mode
with open(output_file, 'wb') as outfile:
    # Loop through each part and append it to the output file
    for part in model_parts:
        part_path = os.path.join(model_parts_dir, part)
        with open(part_path, 'rb') as infile:
            outfile.write(infile.read())

print(f"Model parts merged into {output_file}")